#!/bin/bash

printf "Generating \033[0;34mman page\033[0m documentation..\n"
docker run --rm -v $(pwd):/src pandoc/core --standalone --to man --output /src/pond.1 /src/pond.md
printf "Generating \033[0;34mhtml5\033[0m documentation..\n"
docker run --rm -v $(pwd):/src pandoc/core --standalone --to html5 --output /src/pond.html /src/pond.md
