name: tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published
jobs:
  test-fisher-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch repository history for access to tags in tests
        run: git fetch --prune --unshallow --tags
      - name: Install fish shell
        run: brew install fish
      - name: Install Pond
        uses: fish-shop/install-plugin@main
        with:
          plugin-manager: fisher
          plugins: marcransome/pond
